### ISSUE TITLE
Build fails if log contains non-ASCII char

### ISSUE THREAD

**Issue by pbabinca** [release-engineering/koji-containerbuild#15]
e.g.

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/koji/daemon.py", line 1161, in runTask
    response = (handler.run(),)
  File "/usr/lib/python2.6/site-packages/koji/tasks.py", line 158, in run
    return koji.util.call_with_argcheck(self.handler, self.params, self.opts)
  File "/usr/lib/python2.6/site-packages/koji/util.py", line 154, in call_with_argcheck
    return func(*args, **kwargs)
  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 536, in handler
    logs = self._download_logs(build_id)
  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 266, in _download_logs
    outfile.write(build_log_contents)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 7826: ordinal not in range(128)
```

**Comment by twaugh** [comment]
We decode UTF-8 logs now, should be fine.
