### ISSUE TITLE
A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.

### ISSUE THREAD

**Issue by maxamillion** [release-engineering/koji-containerbuild#25]
I am getting the following error when a build task is executed by the koji-containerbuild plugin (example in [Fedora stage koji](http://koji.stg.fedoraproject.org/koji/taskinfo?taskID=90036398)):

```
2016-03-08 20:56:00,174 [DEBUG] koji.build.BaseTaskHandler: Started by maxamillion
2016-03-08 20:56:00,175 [DEBUG] koji.build.BaseTaskHandler: create_build_args: {'target': 'f24-docker-candidate', 'component': 'cockpit', 'git_uri': 'git://pkgs.stg.fedoraproject.org/docker/cockpit', 'yum_repourls': [], 'architecture': 'a
rmv7hl', 'git_ref': '547da74e1d4e51d9366451bf28aba99a5df0f7c1', 'user': 'maxamillion'}
2016-03-08 20:56:00,175 [DEBUG] koji.build.BaseTaskHandler.osbs: osbs logger installed
2016-03-08 20:56:00,423 [INFO] koji.build.BaseTaskHandler.osbs.core: using basic authentication
2016-03-08 20:56:00,604 [DEBUG] koji.TaskManager: Local buildroots: 0
2016-03-08 20:56:00,605 [DEBUG] koji.TaskManager: Active buildroots: 0
2016-03-08 20:56:00,605 [DEBUG] koji.TaskManager: Expired/stray buildroots: 0
2016-03-08 20:56:00,605 [INFO] koji.TaskManager: pids: {90036366: 14857, 90036367: 14882}
2016-03-08 20:56:00,631 [DEBUG] koji.build: Scrubbing files in /var/tmp/koji/tasks/6367/90036367
2016-03-08 20:56:00,637 [DEBUG] koji.build: Scrubbing directories in /var/tmp/koji/tasks/6367/90036367
2016-03-08 20:56:00,645 [WARNING] koji.TaskManager: TRACEBACK: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/koji/daemon.py", line 1161, in runTask
    response = (handler.run(),)
  File "/usr/lib/python2.7/site-packages/koji/tasks.py", line 158, in run
    return koji.util.call_with_argcheck(self.handler, self.params, self.opts)
  File "/usr/lib/python2.7/site-packages/koji/util.py", line 154, in call_with_argcheck
    return func(*args, **kwargs)
  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 479, in handler
    **create_build_args
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 37, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 346, in create_build
    return self.create_prod_build(**kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 48, in catch_exceptions
    raise OsbsException(cause=ex, traceback=sys.exc_info()[2])
OsbsException: Exception(u"Error connecting to https://osbs-dev.fedorainfracloud.org:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client: (<pycurl.Curl object at 0x34718b0>, 35, 'A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.')",)

Original traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 37, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 294, in create_prod_build
    response = self._create_build_config_and_build(build_request)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 195, in _create_build_config_and_build
    running_builds = self._get_running_builds_for_build_config(build_config_name)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 167, in _get_running_builds_for_build_config
    all_builds_for_bc = self.os.list_builds(build_config_id=build_config_id).json()['items']
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 356, in list_builds
    return self._get(url)
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 167, in _get
    headers, kwargs = self._request_args(with_auth, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 138, in _request_args
    self.get_oauth_token()
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 185, in get_oauth_token
    username=self.username, password=self.password)
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 168, in _get
    return self._con.get(url, headers=headers, verify_ssl=self.verify_ssl, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/http.py", line 105, in get
    return self.request(url, "get", **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/http.py", line 118, in request
    stream = HttpStream(url, *args, verbose=self.verbose, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/http.py", line 242, in __init__
    self._perform()
  File "/usr/lib/python2.7/site-packages/osbs/http.py", line 261, in _perform
    raise Exception("Error connecting to %s: %s" % (self.url, err_obj))
Exception(u"Error connecting to https://osbs-dev.fedorainfracloud.org:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client: (<pycurl.Curl object at 0x34718b0>, 35, 'A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.')",)
```

However I am able to execute a build from this koji builder host using osbs-client `osbs build` and it succeeds just fine.

I can also execute a build using the same osbs api calls that I see koji-containerbuild using:

```
>>> cba = {'target': 'f24-docker-candidate', 'component': 'cockpit', 'git_uri': 'git://pkgs.stg.fedoraproject.org/docker/cockpit', 'yum_repourls': [], 'architecture': 'armv7hl', 'git_ref': '547da74e1d4e51d9366451bf28aba99a5df0f7c1', 'user': 'maxamillion'}
>>> os_conf = Configuration()
>>> build_conf = Configuration()                                                                                       
>>> _osbs = OSBS(os_conf, build_conf)                                                                                  
>>> build_response = _osbs.create_build( **cba )                                                                       
2016-03-09 16:25:11,568 - osbs.conf - WARNING - u'builder_build_json_dir' not found, falling back u'build_json_dir'
>>> build_id = build_response.get_build_name()
>>> response = _osbs.wait_for_build_to_finish(build_id)
>>> response.is_succeeded()
True
```

**Comment by TomasTomecek** [comment]
It looks like that koji builder doesn't trust the certificate openshift master is using. Neither does my laptop:

```
$ curl https://osbs-dev.fedorainfracloud.org:8443
curl: (60) Peer's certificate issuer has been marked as not trusted by the user.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

$ curl -k https://osbs-dev.fedorainfracloud.org:8443
{
  "paths": [
    "/api",
    "/api/v1",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/healthz/ready",
    "/logs/",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/swaggerapi/"
  ]
}%
```

`$ openssl` to the rescue:

```
$ openssl s_client -showcerts -connect osbs-dev.fedorainfracloud.org:8443
CONNECTED(00000003)
depth=1 CN = openshift-signer@1454016400
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/CN=127.0.0.1
   i:/CN=openshift-signer@1454016400
-----BEGIN CERTIFICATE-----
MIID9zCCAt+gAwIBAgIBBjANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE0NTQwMTY0MDAwHhcNMTYwMTI4MjEyNjQxWhcNMTgwMTI3
MjEyNjQyWjAUMRIwEAYDVQQDEwkxMjcuMC4wLjEwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCr+cF39iNhr+WU9Itp4DQiu/Fy/WbKH9pcTVm4Hou7enzx
xI9cSE47MnvWLGTaPukn6j30zIA1CW1B9OyQo9Y1bssmz+aXqk+BAP+37cDoTBqG
vGP1PWSQO8d8yHwRoPjuAtTAKCfFMFbJj0D2AmnAyPGWbKW6+AY1wgMQetQ/desJ
WNEtlweQ1y+s9LGPR7t1J+NzCC/9XT442W1YlrnjoTWgePgBRk7/b3KT5Gey2NTN
YjtUFvVJ+yH9lkpCrFTHmTJGhxAIvLofEBfy4T4OhIVD9Mmnjld/cTqlWEVwct8u
/viL4Ld0OiJWKnhLZcuDUE26W8xK+UM2LTQFk77RAgMBAAGjggFAMIIBPDAOBgNV
HQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADCC
AQUGA1UdEQSB/TCB+oIKa3ViZXJuZXRlc4ISa3ViZXJuZXRlcy5kZWZhdWx0ghZr
dWJlcm5ldGVzLmRlZmF1bHQuc3ZjgiRrdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNs
dXN0ZXIubG9jYWyCCWxvY2FsaG9zdIIJb3BlbnNoaWZ0ghFvcGVuc2hpZnQuZGVm
YXVsdIIVb3BlbnNoaWZ0LmRlZmF1bHQuc3ZjgiNvcGVuc2hpZnQuZGVmYXVsdC5z
dmMuY2x1c3Rlci5sb2NhbIIJMTI3LjAuMC4xggwxNzIuMjUuMzIuOTWCCjE3Mi4z
MC4wLjGHBH8AAAGHBKwZIF+HBKweAAEwDQYJKoZIhvcNAQELBQADggEBABv5HCaI
/pyhCQ6LmbwmY1sGVVqiKXpPDT+mbA3PtrEZrB58tOcim5xnoldI0gKoyG6rgKVp
i4VGbaI/FA39hASMup0S9rKmB6onrukDhfiltR1pFIQNXg+pYMQAdQ1YGX5qzcid
sRclfLSJQHNNu70Odfa+BzE+liMW0jHcZN54s4Da5Jm0LvinOSYe86DPRnU8QBRW
N8/RCSfGo364WuDhU+vQ6kszBPrDVzsgK3gA+NkytYyDOYqjPk6El7OPBU0kCCOC
iv3CMpEEiQ4wZNXmYIcP9F2yj0B9xyrqcp69EMqQ9Aqg4oTGw+qgLNbbYSn5ajwb
ElYqzc84VQw1P3w=
-----END CERTIFICATE-----
 1 s:/CN=openshift-signer@1454016400
   i:/CN=openshift-signer@1454016400
-----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE0NTQwMTY0MDAwHhcNMTYwMTI4MjEyNjQwWhcNMjEwMTI2
MjEyNjQxWjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE0NTQwMTY0MDAw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3rsFT8KrM6hyZdAjKyLbq
pSR1MhHi02eCpxkUG5JR48udxpi7Ve+aY5N6sUfYBDdq88iCvCqQWbIEItifT0+t
sXpRGzew6CxcrvwwO7uahzQmyBZ+AFF2TZ77PwDJ3ZEowrK37tJyxC+aujudbMSI
OLvTtYrrBK6yxp1qIjGP5A5/MuuwhV0OIt0dmby523ksHJ8uWZ8Bx90w/gELqmqh
j6Omf8nyucpfz1fYKyYVjyLatRV24hG+OXYoSLKcxhYOcZhWxfMl4kDKJ4xbqiqi
GwOfjNmGPtiT+C9hX7Xfng4sPqEev2Uq4RX3j5VvZoTcqY5rFuDFKBoYEt9lTl+b
AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
SIb3DQEBCwUAA4IBAQBF09LPCyuA9aPqomfnsb9v/XGe4mSz8ZuVuzoU3vrmkeyV
j6OQcrlqjYkx2yaELISUd34Sg7agmTZ9fH8Aue+0C8bkH967Cu7K+IVNFqe8EV0u
TEsZhAAAWxqJmj7H9ROXVhdWuEQbhUlbFOm7Yv32rzQ2JefDLsUSNK4ojI3+/f8j
tRpZm+Tn7UGF6D25cKtBv0pr3ImZZxT1Q6ucj+uKMjoAVKfvOoy5yQ5O0Qv8aMM2
znwWjVer/RTlZJtKIXoejGhZ6lGHbWT9fW7gg5dhqxson1D8K5AE9wc2AgjGMVX4
RMkz4vvoimE1dCNUTzJJT1fIJmp+5oYb78EKfaKu
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=127.0.0.1
issuer=/CN=openshift-signer@1454016400
---
Acceptable client certificate CA names
/CN=openshift-signer@1454016400
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 2448 bytes and written 345 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 25A749EEE6805802C3A2CA14A598F6AD392E091AD93C38EAC4263F4E87769C12
    Session-ID-ctx:
    Master-Key: 0B001EEA67C9468196D096E3C3239D555394FA4632C8106DD1C1149A720D0220F885F05E2F2438F3A557B76AB86F7501
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket:
    0000 - 08 67 5d 79 3a e4 87 5f-bd af 8f 53 52 6b c2 60   .g]y:.._...SRk.`
    0010 - dc 2f 62 b9 ca a9 c5 ff-0b b9 e2 bb ac 8a 47 83   ./b...........G.
    0020 - 99 26 5c ea a5 fe 4f d7-12 90 46 e5 76 63 1a 01   .&\...O...F.vc..
    0030 - a8 bf 8f 1b 97 a5 13 79-25 f7 76 ea 80 b4 fe 77   .......y%.v....w
    0040 - 78 9c 50 5e 47 e7 80 78-af 16 78 f1 b0 86 d8 4a   x.P^G..x..x....J
    0050 - 7a 5a 9d 5f 30 d0 d7 95-16 d2 89 3c 0a 74 98 65   zZ._0......<.t.e
    0060 - d4 40 17 8d ad 20 61 46-b2 b4 45 36 53 a4 d2 6f   .@... aF..E6S..o
    0070 - a6 f9 2a d4 2e 38 88 ae-                          ..*..8..

    Start Time: 1457606371
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
---
```

Indeed this seems to be the default self-signed certificate generated by openshift.

I can see two solutions:

1. generate better certificates and force OpenShift to use them [1]

2. make koji builder trust the certificates [2]


@mmilata, maybe we could even integrate this into ansible playbook


[1] https://docs.openshift.com/enterprise/3.1/install_config/certificate_customization.html
[2] https://www.happyassassin.net/2014/09/06/adding-your-freeipa-servers-ca-certificate-to-the-system-wide-trust-store-on-fedora-and-rhel/

**Comment by maxamillion** [comment]
@TomasTomecek  The koji builder does trust it, we import the CA and `update-ca-trust` 

From the koji builder:
```
[maxamillion@koji01 ~]$ curl https://osbs-dev.fedorainfracloud.org:8443
{
  "paths": [
    "/api",
    "/api/v1",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/healthz/ready",
    "/logs/",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/swaggerapi/"
  ]
}
```

**Comment by maxamillion** [comment]
We spoke on irc, for posterity I'm leaving this information here. The current thought is that this is related to pycurl via a nss bug: https://bugzilla.redhat.com/show_bug.cgi?id=800304

**Comment by mmilata** [comment]
Yeah, seems to be pycurl/curl/nss or rpm bug: https://bugzilla.redhat.com/show_bug.cgi?id=1317691

It can be worked around by setting following environment variable for `kojid`:
```
export NSS_STRICT_NO_FORK=DISABLED
```
I'm not sure if it doesn't have some security implications so I'd recommend not to use it in production.

**Comment by maxamillion** [comment]
@mmilata That doesn't appear to work, I've modified the systemd unit file and it's still happening:

```
[Unit]
Description=Koji build server
Documentation=https://fedoraproject.org/wiki/Koji/ServerHowTo

After=network.target

[Service]
Environment="NSS_STRICT_NO_FORK=DISABLED"
ExecStart=/usr/sbin/kojid \
       --fg \
       --force-lock \
       --verbose

[Install]
WantedBy=multi-user.target
```

**Comment by mmilata** [comment]
@maxamillion I'm sorry, i misspelled the variable name, it's `NSS_STRICT_NOFORK`. I tried it when running kojid by hand on Fedora and it worked.

Per the bugzilla, better solution would be to call `SECMOD_RestartModules(PR_FALSE)` after the fork. I don't know if there's a python module that can do this or we would have to write our own.

**Comment by lcarva** [comment]
osbs-client no longer uses pycurl: https://github.com/projectatomic/osbs-client/pull/458
