### ISSUE TITLE
Need to reinstate getUploadPath()

### ISSUE THREAD

**Issue by twaugh** [release-engineering/koji-containerbuild#33]
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/koji/daemon.py", line 1161, in runTask
    response = (handler.run(),)
  File "/usr/lib/python2.6/site-packages/koji/tasks.py", line 158, in run
    return koji.util.call_with_argcheck(self.handler, self.params, self.opts)
  File "/usr/lib/python2.6/site-packages/koji/util.py", line 154, in call_with_argcheck
    return func(*args, **kwargs)
  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 313, in handler
    self._incremental_upload_logs(pid)
  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 224, in _incremental_upload_logs
    uploadpath = self.getUploadPath()
AttributeError: 'CreateContainerTask' object has no attribute 'getUploadPath'
```

@maxamillion

**Comment by maxamillion** [comment]
:+1:
