### ISSUE TITLE
adding plugin causes tracebacks in httpd error_log

### ISSUE THREAD

**Issue by maxamillion** [release-engineering/koji-containerbuild#9]
I have a local koji environment setup using [kojak](https://github.com/sbadakhc/kojak) as well as the [storage workaround](https://github.com/sbadakhc/kojak/issues/83).

The koji setup is running fine until I attempt to enable the koji-containerbuild plugin and then I get the following errors in `/var/log/httpd/error_log` ... I suspect it's something simple like I'm just missing a config param or something but I'm not sure what

```
[Mon Aug 10 12:03:02 2015] [crit] [client 192.168.122.1] configuration error:  couldn't perform authentication. AuthType not set!: /koji-static/debug.css, referer: http://koji.example.com/koji/
[Mon Aug 10 12:03:39 2015] [error] 2015-08-10 12:03:39,026 [ERROR] m=None u=None p=1692 r=?:? koji.plugins: Traceback (most recent call last):
[Mon Aug 10 12:03:39 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 507, in load_plugins
[Mon Aug 10 12:03:39 2015] [error]     tracker.load(name)
[Mon Aug 10 12:03:39 2015] [error]   File "/usr/lib/python2.6/site-packages/koji/plugin.py", line 74, in load
[Mon Aug 10 12:03:39 2015] [error]     file, pathname, description = imp.find_module(name, self.pathlist(path))
[Mon Aug 10 12:03:39 2015] [error] ImportError: No module named builder_containerbuild
[Mon Aug 10 12:03:39 2015] [error] 
[Mon Aug 10 12:03:39 2015] [error] 2015-08-10 12:03:39,027 [ERROR] m=None u=None p=1692 r=?:? koji: Traceback (most recent call last):
[Mon Aug 10 12:03:39 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 675, in server_setup
[Mon Aug 10 12:03:39 2015] [error]     registry = get_registry(opts, plugins)
[Mon Aug 10 12:03:39 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 782, in get_registry
[Mon Aug 10 12:03:39 2015] [error]     registry.register_plugin(plugins.get(name))
[Mon Aug 10 12:03:39 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 105, in register_plugin
[Mon Aug 10 12:03:39 2015] [error]     for v in vars(plugin).itervalues():
[Mon Aug 10 12:03:39 2015] [error] TypeError: vars() argument must have __dict__ attribute
[Mon Aug 10 12:03:39 2015] [error] 
[Mon Aug 10 12:13:41 2015] [error] 2015-08-10 12:13:41,105 [ERROR] m=None u=None p=1691 r=?:? koji.plugins: Traceback (most recent call last):
[Mon Aug 10 12:13:41 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 507, in load_plugins
[Mon Aug 10 12:13:41 2015] [error]     tracker.load(name)
[Mon Aug 10 12:13:41 2015] [error]   File "/usr/lib/python2.6/site-packages/koji/plugin.py", line 74, in load
[Mon Aug 10 12:13:41 2015] [error]     file, pathname, description = imp.find_module(name, self.pathlist(path))
[Mon Aug 10 12:13:41 2015] [error] ImportError: No module named builder_containerbuild
[Mon Aug 10 12:13:41 2015] [error] 
[Mon Aug 10 12:13:41 2015] [error] 2015-08-10 12:13:41,106 [ERROR] m=None u=None p=1691 r=?:? koji: Traceback (most recent call last):
[Mon Aug 10 12:13:41 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 675, in server_setup
[Mon Aug 10 12:13:41 2015] [error]     registry = get_registry(opts, plugins)
[Mon Aug 10 12:13:41 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 782, in get_registry
[Mon Aug 10 12:13:41 2015] [error]     registry.register_plugin(plugins.get(name))
[Mon Aug 10 12:13:41 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 105, in register_plugin
[Mon Aug 10 12:13:41 2015] [error]     for v in vars(plugin).itervalues():
[Mon Aug 10 12:13:41 2015] [error] TypeError: vars() argument must have __dict__ attribute
[Mon Aug 10 12:13:41 2015] [error] 
[Mon Aug 10 12:15:41 2015] [error] 2015-08-10 12:15:41,635 [ERROR] m=None u=None p=1687 r=?:? koji.plugins: Traceback (most recent call last):
[Mon Aug 10 12:15:41 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 507, in load_plugins
[Mon Aug 10 12:15:41 2015] [error]     tracker.load(name)
[Mon Aug 10 12:15:41 2015] [error]   File "/usr/lib/python2.6/site-packages/koji/plugin.py", line 74, in load
[Mon Aug 10 12:15:41 2015] [error]     file, pathname, description = imp.find_module(name, self.pathlist(path))
[Mon Aug 10 12:15:41 2015] [error] ImportError: No module named builder_containerbuild
[Mon Aug 10 12:15:41 2015] [error] 
[Mon Aug 10 12:15:41 2015] [error] 2015-08-10 12:15:41,636 [ERROR] m=None u=None p=1687 r=?:? koji: Traceback (most recent call last):
[Mon Aug 10 12:15:41 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 675, in server_setup
[Mon Aug 10 12:15:41 2015] [error]     registry = get_registry(opts, plugins)
[Mon Aug 10 12:15:41 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 782, in get_registry
[Mon Aug 10 12:15:41 2015] [error]     registry.register_plugin(plugins.get(name))
[Mon Aug 10 12:15:41 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 105, in register_plugin
[Mon Aug 10 12:15:41 2015] [error]     for v in vars(plugin).itervalues():
[Mon Aug 10 12:15:41 2015] [error] TypeError: vars() argument must have __dict__ attribute
[Mon Aug 10 12:15:41 2015] [error] 
[Mon Aug 10 12:17:42 2015] [error] 2015-08-10 12:17:42,219 [ERROR] m=None u=None p=1685 r=?:? koji.plugins: Traceback (most recent call last):
[Mon Aug 10 12:17:42 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 507, in load_plugins
[Mon Aug 10 12:17:42 2015] [error]     tracker.load(name)
[Mon Aug 10 12:17:42 2015] [error]   File "/usr/lib/python2.6/site-packages/koji/plugin.py", line 74, in load
[Mon Aug 10 12:17:42 2015] [error]     file, pathname, description = imp.find_module(name, self.pathlist(path))
[Mon Aug 10 12:17:42 2015] [error] ImportError: No module named builder_containerbuild
[Mon Aug 10 12:17:42 2015] [error] 
[Mon Aug 10 12:17:42 2015] [error] 2015-08-10 12:17:42,220 [ERROR] m=None u=None p=1685 r=?:? koji: Traceback (most recent call last):
[Mon Aug 10 12:17:42 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 675, in server_setup
[Mon Aug 10 12:17:42 2015] [error]     registry = get_registry(opts, plugins)
[Mon Aug 10 12:17:42 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 782, in get_registry
[Mon Aug 10 12:17:42 2015] [error]     registry.register_plugin(plugins.get(name))
[Mon Aug 10 12:17:42 2015] [error]   File "/usr/share/koji-hub/kojixmlrpc.py", line 105, in register_plugin
[Mon Aug 10 12:17:42 2015] [error]     for v in vars(plugin).itervalues():
[Mon Aug 10 12:17:42 2015] [error] TypeError: vars() argument must have __dict__ attribute
[Mon Aug 10 12:17:42 2015] [error] 
```

**Comment by pbabinca** [comment]
Please show me your `kojid.conf` which enables that plugin.

**Comment by maxamillion** [comment]
```
[kojid]
; The number of seconds to sleep between tasks
; sleeptime=15

; The maximum number of jobs that kojid will handle at a time
maxjobs=20

; The minimum amount of free space (in MBs) required for each build root
minspace=1024

; The directory root where work data can be found from the koji hub
; topdir=/mnt/koji

; The directory root for temporary storage
; workdir=/tmp/koji

; The directory root for mock
; mockdir=/var/lib/mock

; The user to run as when doing builds
; mockuser=kojibuilder

; The vendor to use in rpm headers
; vendor=Koji

; The packager to use in rpm headers
; packager=Koji

; The distribution to use in rpm headers
; distribution=Koji

; The _host string to use in mock
; mockhost=koji-linux-gnu

; Timeout for build duration (24 hours)
; rpmbuild_timeout=86400

; The URL for the xmlrpc server
server=http://devops.example.com/kojihub

; The URL for the file access
topurl=http://devops.example.com/kojifiles

; A space-separated list of tuples from which kojid is allowed to checkout.
; The format of those tuples is:
;
;     host:repository[:use_common[:source_cmd]]
;
; Incorrectly-formatted tuples will be ignored.
;
; If use_common is not present, kojid will attempt to checkout a common/
; directory from the repository.  If use_common is set to no, off, false, or 0,
; it will not attempt to checkout a common/ directory.
;
; source_cmd is a shell command (args separated with commas instead of spaces)
; to run before building the srpm. It is generally used to retrieve source
; files from a remote location.  If no source_cmd is specified, "make sources"
; is run by default.
allowed_scms=devops.example.com:/rpms/*:false:rhpkg,sources svn.apache.org:/repos/*:no git.app.eng.bos.redhat.com:*:false:rhpkg,sources git.engineering.redhat.com:*:false:rhpkg,sources github.com:*:false:rhpkg,sources forge.fusesource.com:*:false:rhpkg,sources

; The mail host to use for sending email notifications
smtphost=devops.example.com

; The From address used when sending email notifications
from_addr=Koji Build System <buildsys@localdomain>

;configuration for Kerberos authentication

;the format of the principal used by the build hosts
;%s will be replaced by the FQDN of the host
;host_principal_format = compile/%s@EXAMPLE.COM

;location of the keytab
;keytab = /etc/kojid/kojid.keytab

;the service name of the principal being used by the hub
;krbservice = host

;configuration for SSL authentication

;client certificate
cert = /etc/pki/koji/kojibuilder.pem

;certificate of the CA that issued the client certificate
ca = /etc/pki/koji/koji_ca_cert.crt

;certificate of the CA that issued the HTTP server certificate
serverca = /etc/pki/koji/koji_ca_cert.crt
```

**Comment by pbabinca** [comment]
You are completely missing `koji-containerbuild` *builder* plugin in your config. Please follow instructions in readme file to enable the plugin: https://github.com/release-engineering/koji-containerbuild#plugin-installation

Please show me also your `hub.conf` if you have the *hub* plugin configured correctly.

**Comment by maxamillion** [comment]
```
[hub]

## ConfigParser style config file, similar to ini files
## http://docs.python.org/library/configparser.html
##
## Note that multiline values can be set by indenting subsequent lines
## (which means you should not indent regular lines)

## Basic options ##
DBName = koji
DBUser = koji
#DBHost = localhost.localdomain
#DBPass = koji
KojiDir = /mnt/koji


##  Kerberos authentication options  ##

# AuthPrincipal = host/kojihub@EXAMPLE.COM
# AuthKeytab = /etc/koji.keytab
# ProxyPrincipals = koji/kojiweb@EXAMPLE.COM
## format string for host principals (%s = hostname)
# HostPrincipalFormat = compile/%s@EXAMPLE.COM

## end Kerberos auth configuration


##  SSL client certificate auth configuration  ##
#note: ssl auth may also require editing the httpd config (conf.d/kojihub.conf)

## the client username is the common name of the subject of their client certificate
# DNUsernameComponent = CN
## separate multiple DNs with |
# ProxyDNs = /C=US/ST=Massachusetts/O=Example Org/OU=Example User/CN=example/emailAddress=example@example.com
ProxyDNs = /C=XX/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=kojiweb/emailAddress=devops.example.com

## end SSL client certificate auth configuration


##  Other options  ##
LoginCreatesUser = On
KojiWebURL = http://kojiweb.localdomain/koji
# The domain name that will be appended to Koji usernames
# when creating email notifications
#EmailDomain = example.com
# whether to send the task owner and package owner email or not on success.  this still goes to watchers
NotifyOnSuccess = True
## Disables all notifications
DisableNotifications = True

## Extended features
## Support Maven builds
EnableMaven = True
## Support Windows builds
# EnableWin = False

## Koji hub plugins
## The path where plugins are found
PluginPath = /usr/lib/koji-hub-plugins
## A space-separated list of plugins to load
Plugins = builder_containerbuild

## If KojiDebug is on, the hub will be /very/ verbose and will report exception
## details to clients for anticipated errors (i.e. koji's own exceptions --
## subclasses of koji.GenericError).
# KojiDebug = On

## Determines how much detail about exceptions is reported to the client (via faults)
## Meaningful values:
##   normal - a basic traceback (format_exception)
##   extended - an extended traceback (format_exc_plus)
##   anything else - no traceback, just the error message
## The extended traceback is intended for debugging only and should NOT be
## used in production, since it may contain sensitive information.
# KojiTraceback = normal

## These options are intended for planned outages
# ServerOffline = False
# OfflineMessage = temporary outage
# LockOut = False
## If ServerOffline is True, the server will always report a ServerOffline fault (with
## OfflineMessage as the fault string).
## If LockOut is True, the server will report a ServerOffline fault for all non-admin
```

**Comment by pbabinca** [comment]
> `## The path where plugins are found`
> `PluginPath = /usr/lib/koji-hub-plugins`

Make sure you have `hub_containerbuild.py` in this path ^.

**Comment by maxamillion** [comment]
Yeah, I got that fixed. I'm running into a very different issue now though. Will close this and open another if I can't get it sorted.
